import React from 'react';
import { EvidenceBreakdown } from '../types';
import { ShieldCheck, Info, CheckCircle2, Clock, XCircle, BarChart3, AlertCircle, Sparkles, Users } from 'lucide-react';

interface EvidencePanelProps {
  evidence: EvidenceBreakdown;
}

export const EvidencePanel: React.FC<EvidencePanelProps> = ({ evidence }) => {
  const isZeroCommunity = evidence.isAiGuidanceOnly || evidence.totalRealAnalyzed === 0 || evidence.totalAnalyzed === 0;
  const total = evidence.totalRealAnalyzed ?? evidence.totalAnalyzed ?? 0;
  const posPct = total > 0 ? Math.round((evidence.positiveOutcomes / total) * 100) : 0;
  const mixPct = total > 0 ? Math.round((evidence.mixedOutcomes / total) * 100) : 0;
  const unsPct = total > 0 ? Math.round((evidence.unsuccessfulOutcomes / total) * 100) : 0;

  if (isZeroCommunity) {
    return (
      <div className="bg-white rounded-2xl border border-slate-200/90 p-5 sm:p-6 shadow-2xs space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3.5">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-700 border border-indigo-200 flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-sm sm:text-base text-slate-900">
                Evidence Base & Status
              </h3>
              <span className="text-[11px] text-slate-500 font-medium">Empirical Community Grounding</span>
            </div>
          </div>

          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-50 text-amber-900 border border-amber-200">
            <Users className="w-3.5 h-3.5 text-amber-700" />
            <span>0 Real Community Cases</span>
          </div>
        </div>

        {/* The required Empty Community Experience Callout */}
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs space-y-2">
          <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
            <AlertCircle className="w-4 h-4 text-indigo-600" />
            <span>No community experiences yet</span>
          </div>
          <p className="text-slate-600 leading-relaxed font-medium">
            You're among the first people building the Common Mind experience knowledge base.
          </p>
          <p className="text-slate-500 leading-relaxed text-[11px]">
            Because no real human experiences exist in the database for this scenario yet, the recommendation above is labeled <strong className="text-slate-700">GENERAL AI GUIDANCE</strong>. It is generated by AI analytical reasoning and is <strong className="text-slate-700">NOT</strong> based on community experience.
          </p>
        </div>

        {/* Real counts strictly rendered as 0 */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex flex-col justify-between">
            <span className="text-[11px] font-medium text-slate-500">Real Cases Analyzed</span>
            <div className="text-xl font-bold text-slate-900 mt-1">
              0 <span className="text-[11px] font-normal text-slate-400">cases</span>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex flex-col justify-between">
            <span className="text-[11px] font-medium text-slate-500">Positive Outcomes</span>
            <div className="text-xl font-bold text-slate-900 mt-1">
              0 <span className="text-[11px] font-normal text-slate-400">(0%)</span>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex flex-col justify-between">
            <span className="text-[11px] font-medium text-slate-500">Mixed Outcomes</span>
            <div className="text-xl font-bold text-slate-900 mt-1">
              0 <span className="text-[11px] font-normal text-slate-400">(0%)</span>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex flex-col justify-between">
            <span className="text-[11px] font-medium text-slate-500">Unsuccessful Cases</span>
            <div className="text-xl font-bold text-slate-900 mt-1">
              0 <span className="text-[11px] font-normal text-slate-400">(0%)</span>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="flex items-start gap-2 pt-2 border-t border-slate-100 text-xs text-slate-500 leading-relaxed">
          <Info className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />
          <p>
            <strong className="text-slate-700">Data Integrity Principle:</strong> Common Mind never invents fake community numbers. Once you try this plan and click <em>Report Outcome</em>, your trial will become the first verified real experience in this category.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl border border-slate-200/90 p-5 sm:p-6 shadow-2xs space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3.5">
        <div className="flex items-center gap-2">
          <BarChart3 className="w-5 h-5 text-indigo-600" />
          <h3 className="font-bold text-sm sm:text-base text-slate-900">
            Evidence Base & Verification
          </h3>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500 font-medium">Evidence Confidence:</span>
          <div className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-emerald-50 text-emerald-800 border border-emerald-200">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
            <span>{evidence.confidencePercentage}%</span>
          </div>
        </div>
      </div>

      {/* Outcome distribution counters */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
        <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex flex-col justify-between">
          <span className="text-xs font-medium text-slate-500">Real Community Cases</span>
          <div className="text-xl font-bold text-slate-900 mt-1">
            {total} <span className="text-xs font-normal text-slate-500">cases</span>
          </div>
        </div>

        <div className="p-3 rounded-xl bg-emerald-50/60 border border-emerald-100 flex flex-col justify-between">
          <div className="flex items-center justify-between text-xs font-semibold text-emerald-800">
            <span>Positive Outcomes</span>
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
          </div>
          <div className="text-xl font-bold text-emerald-900 mt-1">
            {evidence.positiveOutcomes}{' '}
            <span className="text-xs font-medium text-emerald-700">({posPct}%)</span>
          </div>
        </div>

        <div className="p-3 rounded-xl bg-amber-50/60 border border-amber-100 flex flex-col justify-between">
          <div className="flex items-center justify-between text-xs font-semibold text-amber-800">
            <span>Mixed Outcomes</span>
            <Clock className="w-3.5 h-3.5 text-amber-600" />
          </div>
          <div className="text-xl font-bold text-amber-900 mt-1">
            {evidence.mixedOutcomes}{' '}
            <span className="text-xs font-medium text-amber-700">({mixPct}%)</span>
          </div>
        </div>

        <div className="p-3 rounded-xl bg-rose-50/60 border border-rose-100 flex flex-col justify-between">
          <div className="flex items-center justify-between text-xs font-semibold text-rose-800">
            <span>Unsuccessful</span>
            <XCircle className="w-3.5 h-3.5 text-rose-600" />
          </div>
          <div className="text-xl font-bold text-rose-900 mt-1">
            {evidence.unsuccessfulOutcomes}{' '}
            <span className="text-xs font-medium text-rose-700">({unsPct}%)</span>
          </div>
        </div>
      </div>

      {/* Visual Progress Bar */}
      <div className="space-y-1.5 pt-1">
        <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden flex">
          <div style={{ width: `${posPct}%` }} className="bg-emerald-500 h-full transition-all" title="Positive" />
          <div style={{ width: `${mixPct}%` }} className="bg-amber-400 h-full transition-all" title="Mixed" />
          <div style={{ width: `${unsPct}%` }} className="bg-rose-400 h-full transition-all" title="Unsuccessful" />
        </div>
      </div>

      {/* Essential Disclaimer */}
      <div className="flex items-start gap-2 pt-2 border-t border-slate-100 text-xs text-slate-500 leading-relaxed">
        <Info className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />
        <p>
          <strong className="text-slate-700">Important:</strong> {evidence.disclaimer} Common Mind synthesizes historical patterns rather than predicting guaranteed outcomes.
        </p>
      </div>
    </div>
  );
};
